### ISSUE TITLE
How to deal with component @Output() events?

### ISSUE THREAD

**Issue by Halt001** [angular/playground#1]
Angular Playground is awesome. It didn't take long to convince the team to use this. Much appreciated!

One thing still puzzles me. What can we do with component outputs. I want to be able to see that the events are emitted as expected but where can I bind them to? Do I need to create a dummy container component? Developing dummy components  for debugging would somewhat detract from the super un-intrusive way Playground works.

I also tried to add a function to the context object with a console.log and bind it like this: `(filterChange)="filterChange($event)"` but that didn't work.

Am I missing an obvious way to do this?

**Comment by trotyl** [comment]
Wrong repo, you're looking for https://github.com/socreate/angular-playground.

**Comment by Halt001** [comment]
You're right, sorry!
